# 只写端口号，前面留空，代表监听本机所有可用的IPv4和IPv6地址
listen: ":443"
log_level: "info"
default_backend: "127.0.0.1:8080"
rules:
  - sni: "secret.core.service.yourdomain.com"
    backend: "127.0.0.1:9999"
  - sni: "www.your-main-domain.com"
    backend: "127.0.0.1:8080"